### ISSUE TITLE
Error Since November 19, 2022 Update

### ISSUE THREAD

**Issue by ucdscott** [pfmiller0/Hubitat#3]
The most recent version (January 16, 2023) of PurpleAir AQI Virtual Sensor.groovy produces an error:

`java.lang.NullPointerException: null on line 323 (method httpResponse)`

Tried the November 19th, 2022 release, same result.

The Aug 20, 2022 release does not appear to generate the error.

**Comment by pfmiller0** [comment]
Fixed in latest version

**Comment by ucdscott** [comment]
Thank you. I haven't seen any errors since updating to the latest version.
